package pojos;
// Generated 15 de des. 2023, 16:03:53 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Assignatura generated by hbm2java
 */
public class Assignatura implements java.io.Serializable {

	private String codAsig;
	private String nom;
	private Set alumnes = new HashSet(0);

	public Assignatura() {
	}

	public Assignatura(String codAsig, String nom, Set alumnes) {
		this.codAsig = codAsig;
		this.nom = nom;
		this.alumnes = alumnes;
	}

	public String getCodAsig() {
		return this.codAsig;
	}

	public void setCodAsig(String codAsig) {
		this.codAsig = codAsig;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Set getAlumnes() {
		return this.alumnes;
	}

	public void setAlumnes(Set alumnes) {
		this.alumnes = alumnes;
	}

}
