package pojos;
// Generated 15 de des. 2023, 16:03:53 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departaments generated by hbm2java
 */
public class Departaments implements java.io.Serializable {

	private int deptNo;
	private String deptNom;
	private String deptCiutat;
	private Set empleatses = new HashSet(0);

	public Departaments() {
	}

	public Departaments(int deptNo, String deptNom, String deptCiutat, Set empleatses) {
		this.deptNo = deptNo;
		this.deptNom = deptNom;
		this.deptCiutat = deptCiutat;
		this.empleatses = empleatses;
	}

	public int getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(int deptNo) {
		this.deptNo = deptNo;
	}

	public String getDeptNom() {
		return this.deptNom;
	}

	public void setDeptNom(String deptNom) {
		this.deptNom = deptNom;
	}

	public String getDeptCiutat() {
		return this.deptCiutat;
	}

	public void setDeptCiutat(String deptCiutat) {
		this.deptCiutat = deptCiutat;
	}

	public Set getEmpleatses() {
		return this.empleatses;
	}

	public void setEmpleatses(Set empleatses) {
		this.empleatses = empleatses;
	}

	@Override
	public String toString() {
		return "[deptNo=" + deptNo + ", deptNom=" + deptNom + ", deptCiutat=" + deptCiutat + "]";
	}

}
