package pojos;
// Generated 15 de des. 2023, 16:03:53 by Hibernate Tools 6.3.1.Final

import java.sql.Date;

/**
 * Empleats generated by hbm2java
 */
public class Empleats implements java.io.Serializable {

	private int empNo;
	private Departaments departaments;
	private String cognoms;
	private String nom;
	private Date dataAlta;
	private Long sou;
	private Long comissio;

	public Empleats() {
	}

	public Empleats(int empNo, Departaments departaments, String cognoms, String nom, Date dataAlta, Long sou,
			Long comissio) {
		this.empNo = empNo;
		this.departaments = departaments;
		this.cognoms = cognoms;
		this.nom = nom;
		this.dataAlta = dataAlta;
		this.sou = sou;
		this.comissio = comissio;
	}

	public int getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(int empNo) {
		this.empNo = empNo;
	}

	public Departaments getDepartaments() {
		return this.departaments;
	}

	public void setDepartaments(Departaments departaments) {
		this.departaments = departaments;
	}

	public String getCognoms() {
		return this.cognoms;
	}

	public void setCognoms(String cognoms) {
		this.cognoms = cognoms;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Date getDataAlta() {
		return this.dataAlta;
	}

	public void setDataAlta(Date dataAlta) {
		this.dataAlta = dataAlta;
	}

	public Long getSou() {
		return this.sou;
	}

	public void setSou(Long sou) {
		this.sou = sou;
	}

	public Long getComissio() {
		return this.comissio;
	}

	public void setComissio(Long comissio) {
		this.comissio = comissio;
	}

}
