CREATE TABLE PLANTILLA(
    HOSPITAL_COD TINYINT(2) CONSTRAINT PLANTILLA_SALA_FK FOREIGN KEY REFERENCES SALA,
    SALA_COD TINYINT(2),
    EMPLEAT_NO SMALLINT(4) CONSTRAINT PLANTILLA_PK PRIMARY KEY,
    COGNOM VARCHAR(15) NOT NULL,
    FUNCIO VARCHAR(10),
    TORN VARCHAR(1) CONSTRAINT TORN_CH CHECK(TORN='M',TORN='T',TORN='N'),
    SALARI INT(10)
);