package pojos;
// Generated 10 feb 2024 20:26:02 by Hibernate Tools 6.3.1.Final

/**
 * Vehicles generated by hbm2java
 */
public class Vehicles implements java.io.Serializable {

	private int vehicleId;
	private Brands brands;
	private Owners owners;
	private String model;
	private String licensePlate;

	public Vehicles() {
	}

	public Vehicles(int vehicleId, Brands brands, Owners owners, String model, String licensePlate) {
		this.vehicleId = vehicleId;
		this.brands = brands;
		this.owners = owners;
		this.model = model;
		this.licensePlate = licensePlate;
	}

	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	public Brands getBrands() {
		return this.brands;
	}

	public void setBrands(Brands brands) {
		this.brands = brands;
	}

	public Owners getOwners() {
		return this.owners;
	}

	public void setOwners(Owners owners) {
		this.owners = owners;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	@Override
	public String toString() {
		return "Vehicles [vehicleId=" + vehicleId + ", brands=" + brands + ", owners=" + owners + ", model=" + model
				+ ", licensePlate=" + licensePlate + "]";
	}

}
