package pojos;
// Generated 15 de des. 2023, 16:03:53 by Hibernate Tools 6.3.1.Final

/**
 * Usuaris generated by hbm2java
 */
public class Usuaris implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int userid;
	private String pwd;
	private String nom;
	private String cognoms;
	private String email;

	public Usuaris() {
	}

	public Usuaris(int userid, String pwd, String nom, String cognoms, String email) {
		this.userid = userid;
		this.pwd = pwd;
		this.nom = nom;
		this.cognoms = cognoms;
		this.email = email;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getCognoms() {
		return this.cognoms;
	}

	public void setCognoms(String cognoms) {
		this.cognoms = cognoms;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "[userid=" + userid + ", pwd=" + pwd + ", nom=" + nom + ", cognoms=" + cognoms + ", email=" + email
				+ "]";
	}

}
