package pojos;
// Generated 10 feb 2024 20:26:02 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Brands generated by hbm2java
 */
public class Brands implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer brandId;
	private String brandName;
	private String country;
	private Set<Vehicles> vehicleses = new HashSet<>(0);

	public Brands() {
	}

	public Brands(Integer brandId, String brandName, String country, Set<Vehicles> vehicleses) {
		this.brandId = brandId;
		this.brandName = brandName;
		this.country = country;
		this.vehicleses = vehicleses;
	}

	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Set<Vehicles> getVehicleses() {
		return this.vehicleses;
	}

	public void setVehicleses(Set<Vehicles> vehicleses) {
		this.vehicleses = vehicleses;
	}

	@Override
	public String toString() {
		return "Brands [brandId=" + brandId + ", brandName=" + brandName + ", country=" + country + "]";
	}

}
