package pojos;
// Generated 10 feb 2024 20:26:02 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Owners generated by hbm2java
 */
public class Owners implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int ownerId;
	private String firstName;
	private String lastName;
	private String phoneNumber;
	private String email;
	private Set<Vehicles> vehicleses = new HashSet<>(0);

	public Owners() {
	}

	public Owners(int ownerId, String firstName, String lastName, String phoneNumber, String email,
			Set<Vehicles> vehicleses) {
		this.ownerId = ownerId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.vehicleses = vehicleses;
	}

	public int getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<Vehicles> getVehicleses() {
		return this.vehicleses;
	}

	public void setVehicleses(Set<Vehicles> vehicleses) {
		this.vehicleses = vehicleses;
	}

	@Override
	public String toString() {
		return "Owners [ownerId=" + ownerId + ", firstName=" + firstName + ", lastName=" + lastName + ", phoneNumber="
				+ phoneNumber + ", email=" + email + "]";
	}
}
